master:
  image: bitnami/redis:6.0
  environment: 
    - ALLOW_EMPTY_PASSWORD=yes
slave:
  image: bitnami/redis:6.0
  environment: 
    - ALLOW_EMPTY_PASSWORD=yes
  command: redis-server --replicaof redis-master 6379
  links:
    - master:redis-master
sentinel:
  build: sentinel
  environment:
    - SENTINEL_DOWN_AFTER=100
    # - SENTINEL_FAILOVER=10000
    # - SENTINEL_QUORUM=1
    # - SENTINEL_PORT=26379
    # - REDIS_MASTER=redis-master
    # - REDIS_SLAVE=redis-slave
    # - INSTANCE=mymaster
  links:
    - master:redis-master
    - slave:redis-slave
