master:
  image: bitnami/redis:6.0
  environment: 
    - ALLOW_EMPTY_PASSWORD=yes
    - REDIS_AOF_ENABLED=no
    - REDIS_REPLICATION_MODE=master
  # volumes:
  #   - "./data/master:/bitnami/redis/data"
slave:
  image: bitnami/redis:6.0
  environment: 
    - ALLOW_EMPTY_PASSWORD=yes
    - REDIS_AOF_ENABLED=no
    - REDIS_REPLICATION_MODE=slave
    - REDIS_MASTER_HOST=redis-master
    - REDIS_MASTER_PORT_NUMBER=6379
  # volumes:
  #   - "./data/slave:/bitnami/redis/data"
  links:
    - master:redis-master
sentinel:
  build: sentinel
  environment:
    - SENTINEL_DOWN_AFTER=100
    # - SENTINEL_FAILOVER=10000
    # - SENTINEL_QUORUM=1
    # - SENTINEL_PORT=26379
    # - REDIS_MASTER=redis-master
    # - REDIS_SLAVE=redis-slave
    # - INSTANCE=mymaster
  links:
    - master:redis-master
    - slave:redis-slave